-- V1__create_schema_medhub.sql
-- Schema inicial do MedHub para PostgreSQL + Flyway.
-- Compatível com as entidades JPA do projeto: Usuario, Medico, Recepcionista,
-- Administrador, Paciente, ChaveAcesso, Agenda, Consulta, CancelamentoConsulta,
-- HistoricoClinico, Exame, ArquivoExame e LogAlteracaoPerfil.

-- =========================================================
-- USUÁRIOS INTERNOS E HERANÇA JOINED
-- =========================================================

CREATE TABLE usuarios (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome VARCHAR(120) NOT NULL,
    cpf VARCHAR(14) NOT NULL,
    email VARCHAR(150) NOT NULL,
    senha VARCHAR(255) NOT NULL,
    perfil VARCHAR(30) NOT NULL,
    ativo BOOLEAN NOT NULL DEFAULT TRUE,

    CONSTRAINT pk_usuarios PRIMARY KEY (id),
    CONSTRAINT uk_usuario_cpf UNIQUE (cpf),
    CONSTRAINT uk_usuario_email UNIQUE (email),
    CONSTRAINT ck_usuario_perfil CHECK (perfil IN ('MEDICO', 'RECEPCIONISTA', 'ADMINISTRADOR'))
);

CREATE TABLE medicos (
    usuario_id BIGINT NOT NULL,
    crm VARCHAR(30) NOT NULL,
    especialidade VARCHAR(100) NOT NULL,

    CONSTRAINT pk_medicos PRIMARY KEY (usuario_id),
    CONSTRAINT uk_medico_crm UNIQUE (crm),
    CONSTRAINT fk_medicos_usuarios FOREIGN KEY (usuario_id)
        REFERENCES usuarios (id)
        ON DELETE CASCADE
);

CREATE TABLE recepcionistas (
    usuario_id BIGINT NOT NULL,

    CONSTRAINT pk_recepcionistas PRIMARY KEY (usuario_id),
    CONSTRAINT fk_recepcionistas_usuarios FOREIGN KEY (usuario_id)
        REFERENCES usuarios (id)
        ON DELETE CASCADE
);

CREATE TABLE administradores (
    usuario_id BIGINT NOT NULL,

    CONSTRAINT pk_administradores PRIMARY KEY (usuario_id),
    CONSTRAINT fk_administradores_usuarios FOREIGN KEY (usuario_id)
        REFERENCES usuarios (id)
        ON DELETE CASCADE
);

-- =========================================================
-- PACIENTES E CHAVE DE ACESSO
-- =========================================================

CREATE TABLE pacientes (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome_completo VARCHAR(120) NOT NULL,
    cpf VARCHAR(14) NOT NULL,
    data_nascimento DATE NOT NULL,
    telefone VARCHAR(20) NOT NULL,
    email VARCHAR(150),

    CONSTRAINT pk_pacientes PRIMARY KEY (id),
    CONSTRAINT uk_paciente_cpf UNIQUE (cpf)
);

CREATE TABLE chaves_acesso (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    codigo VARCHAR(80) NOT NULL,
    data_criacao TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    data_expiracao TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    ativa BOOLEAN NOT NULL DEFAULT TRUE,
    paciente_id BIGINT NOT NULL,

    CONSTRAINT pk_chaves_acesso PRIMARY KEY (id),
    CONSTRAINT uk_chave_acesso_codigo UNIQUE (codigo),
    CONSTRAINT uk_chave_acesso_paciente UNIQUE (paciente_id),
    CONSTRAINT fk_chaves_acesso_pacientes FOREIGN KEY (paciente_id)
        REFERENCES pacientes (id)
        ON DELETE CASCADE
);

-- =========================================================
-- AGENDA E CONSULTAS
-- =========================================================

CREATE TABLE agendas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    medico_id BIGINT NOT NULL,
    hora_inicio TIME(6) WITHOUT TIME ZONE NOT NULL DEFAULT TIME '08:00:00',
    hora_fim TIME(6) WITHOUT TIME ZONE NOT NULL DEFAULT TIME '18:00:00',
    intervalo_minutos INTEGER NOT NULL DEFAULT 30,

    CONSTRAINT pk_agendas PRIMARY KEY (id),
    CONSTRAINT uk_agenda_medico UNIQUE (medico_id),
    CONSTRAINT fk_agendas_medicos FOREIGN KEY (medico_id)
        REFERENCES medicos (usuario_id),
    CONSTRAINT ck_agenda_intervalo_positivo CHECK (intervalo_minutos > 0),
    CONSTRAINT ck_agenda_horario_valido CHECK (hora_fim > hora_inicio)
);

CREATE TABLE consultas (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    data_hora TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    status VARCHAR(30) NOT NULL DEFAULT 'AGENDADA',
    paciente_id BIGINT NOT NULL,
    medico_id BIGINT NOT NULL,
    agenda_id BIGINT,

    CONSTRAINT pk_consultas PRIMARY KEY (id),
    CONSTRAINT ck_consulta_status CHECK (status IN ('AGENDADA', 'CONFIRMADA', 'EM_ATENDIMENTO', 'REALIZADA', 'CANCELADA')),
    CONSTRAINT fk_consultas_pacientes FOREIGN KEY (paciente_id)
        REFERENCES pacientes (id),
    CONSTRAINT fk_consultas_medicos FOREIGN KEY (medico_id)
        REFERENCES medicos (usuario_id),
    CONSTRAINT fk_consultas_agendas FOREIGN KEY (agenda_id)
        REFERENCES agendas (id)
);

CREATE TABLE cancelamentos_consulta (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    data_hora_cancelamento TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL,
    motivo VARCHAR(500) NOT NULL,
    consulta_id BIGINT NOT NULL,

    CONSTRAINT pk_cancelamentos_consulta PRIMARY KEY (id),
    CONSTRAINT uk_cancelamento_consulta UNIQUE (consulta_id),
    CONSTRAINT fk_cancelamentos_consultas FOREIGN KEY (consulta_id)
        REFERENCES consultas (id)
        ON DELETE CASCADE
);

-- Evita dupla marcação ativa para o mesmo médico no mesmo horário.
-- Consultas canceladas são ignoradas para permitir novo agendamento no mesmo horário.
CREATE UNIQUE INDEX uk_consulta_medico_data_hora_ativa
    ON consultas (medico_id, data_hora)
    WHERE status <> 'CANCELADA';

-- =========================================================
-- HISTÓRICO CLÍNICO
-- =========================================================

CREATE TABLE historicos_clinicos (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    data DATE NOT NULL,
    queixa_principal VARCHAR(500) NOT NULL,
    diagnostico TEXT NOT NULL,
    observacoes TEXT,
    paciente_id BIGINT NOT NULL,
    medico_id BIGINT NOT NULL,

    CONSTRAINT pk_historicos_clinicos PRIMARY KEY (id),
    CONSTRAINT fk_historicos_clinicos_pacientes FOREIGN KEY (paciente_id)
        REFERENCES pacientes (id),
    CONSTRAINT fk_historicos_clinicos_medicos FOREIGN KEY (medico_id)
        REFERENCES medicos (usuario_id)
);

-- =========================================================
-- EXAMES E ARQUIVOS
-- =========================================================

CREATE TABLE arquivos_exame (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    nome_arquivo VARCHAR(255) NOT NULL,
    formato VARCHAR(20) NOT NULL,
    caminho VARCHAR(500) NOT NULL,
    tamanho_bytes BIGINT NOT NULL,

    CONSTRAINT pk_arquivos_exame PRIMARY KEY (id),
    CONSTRAINT ck_arquivo_exame_formato CHECK (formato IN ('PDF', 'IMAGEM', 'TEXTO')),
    CONSTRAINT ck_arquivo_exame_tamanho CHECK (tamanho_bytes >= 0)
);

CREATE TABLE exames (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    tipo VARCHAR(100) NOT NULL,
    data_realizacao DATE NOT NULL,
    resultado_texto TEXT,
    status VARCHAR(30) NOT NULL DEFAULT 'CADASTRADO',
    paciente_id BIGINT NOT NULL,
    medico_solicitante_id BIGINT NOT NULL,
    arquivo_exame_id BIGINT,

    CONSTRAINT pk_exames PRIMARY KEY (id),
    CONSTRAINT ck_exame_status CHECK (status IN ('SOLICITADO', 'CADASTRADO', 'DISPONIVEL', 'CANCELADO')),
    CONSTRAINT uk_exame_arquivo UNIQUE (arquivo_exame_id),
    CONSTRAINT fk_exames_pacientes FOREIGN KEY (paciente_id)
        REFERENCES pacientes (id),
    CONSTRAINT fk_exames_medicos FOREIGN KEY (medico_solicitante_id)
        REFERENCES medicos (usuario_id),
    CONSTRAINT fk_exames_arquivos_exame FOREIGN KEY (arquivo_exame_id)
        REFERENCES arquivos_exame (id)
);

-- =========================================================
-- LOGS DE ALTERAÇÃO DE PERFIL
-- =========================================================

CREATE TABLE logs_alteracao_perfil (
    id BIGINT GENERATED BY DEFAULT AS IDENTITY,
    data_hora TIMESTAMP(6) WITHOUT TIME ZONE NOT NULL DEFAULT CURRENT_TIMESTAMP,
    perfil_anterior VARCHAR(30) NOT NULL,
    perfil_novo VARCHAR(30) NOT NULL,
    usuario_alterado_id BIGINT NOT NULL,
    administrador_id BIGINT NOT NULL,

    CONSTRAINT pk_logs_alteracao_perfil PRIMARY KEY (id),
    CONSTRAINT ck_log_perfil_anterior CHECK (perfil_anterior IN ('MEDICO', 'RECEPCIONISTA', 'ADMINISTRADOR')),
    CONSTRAINT ck_log_perfil_novo CHECK (perfil_novo IN ('MEDICO', 'RECEPCIONISTA', 'ADMINISTRADOR')),
    CONSTRAINT fk_logs_usuario_alterado FOREIGN KEY (usuario_alterado_id)
        REFERENCES usuarios (id),
    CONSTRAINT fk_logs_administradores FOREIGN KEY (administrador_id)
        REFERENCES administradores (usuario_id)
);

-- =========================================================
-- ÍNDICES AUXILIARES PARA CONSULTAS FREQUENTES
-- =========================================================

CREATE INDEX idx_usuarios_perfil ON usuarios (perfil);
CREATE INDEX idx_usuarios_ativo ON usuarios (ativo);
CREATE INDEX idx_usuarios_nome_lower ON usuarios (LOWER(nome));

CREATE INDEX idx_pacientes_nome_completo_lower ON pacientes (LOWER(nome_completo));
CREATE INDEX idx_pacientes_email ON pacientes (email);

CREATE INDEX idx_chaves_acesso_codigo_ativa ON chaves_acesso (codigo, ativa);
CREATE INDEX idx_chaves_acesso_paciente ON chaves_acesso (paciente_id);

CREATE INDEX idx_agendas_medico ON agendas (medico_id);

CREATE INDEX idx_consultas_paciente ON consultas (paciente_id);
CREATE INDEX idx_consultas_medico ON consultas (medico_id);
CREATE INDEX idx_consultas_agenda ON consultas (agenda_id);
CREATE INDEX idx_consultas_data_hora ON consultas (data_hora);
CREATE INDEX idx_consultas_status ON consultas (status);

CREATE INDEX idx_historicos_paciente ON historicos_clinicos (paciente_id);
CREATE INDEX idx_historicos_medico ON historicos_clinicos (medico_id);
CREATE INDEX idx_historicos_data ON historicos_clinicos (data);

CREATE INDEX idx_exames_paciente ON exames (paciente_id);
CREATE INDEX idx_exames_medico_solicitante ON exames (medico_solicitante_id);
CREATE INDEX idx_exames_status ON exames (status);
CREATE INDEX idx_exames_data_realizacao ON exames (data_realizacao);

CREATE INDEX idx_logs_usuario_alterado ON logs_alteracao_perfil (usuario_alterado_id);
CREATE INDEX idx_logs_administrador ON logs_alteracao_perfil (administrador_id);
CREATE INDEX idx_logs_data_hora ON logs_alteracao_perfil (data_hora);
